export * from "./Home";
export * from "./Signup";
export * from "./SignIn";
export * from "./Resetpassword";
export * from "./Otp";
export * from "./Profilesetup";
export * from "./Payment";
export * from './Dashboard'
export * from './Orders'
export * from './Products'
export * from './AddProduct'
export * from './Settings'
export * from './Shop'
export * from './Sales'
export * from './Insights'